artifacts_root : artifacts

data_ingestion:
  root_dit : artifacts_root/data_ingestion
  source_url: https://github.com/gayathrik948/nlp_task1/raw/main/cuisine_data.zip
  local_data_file: artifacts_root/data_ingestion/cuisine_data.zip
  unzip_dir: artifacts_root/data_ingestion