artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url: https://github.com/gayathrik948/nlp_task1/raw/main/cuisine_data.zip
  local_data_file: artifacts/data_ingestion/cuisine_data.zip
  unzip_dir: artifacts/data_ingestion
  unzip_dir_file: artifacts/data_ingestion/cuisine_data.csv
  train_file_dir: artifacts/data_ingestion/train
  test_file_dir: artifacts/data_ingestion/test
  train_file_name: train.csv
  test_file_name: test.csv
  test_size: 0.2
  column_names: ['cuisine_description', 'cuisine']

model_trainer:
  root_dir: artifacts/model_trainer
  train_file_dir_path: artifacts/data_ingestion/train/train.csv
  test_file_dir_path: artifacts/data_ingestion/test/test.csv
  tokenizer_name: distilbert-base-uncased
  column_names: ['cuisine_description', 'cuisine']
  custom_model: artifacts/model_trainer/custom_model
  custom_model_file: artifacts/model_trainer/custom_model

model_prediction:
  root_dir: artifacts/model_prediction
  train_file_dir_path: artifacts/data_ingestion/train/train.csv
  test_file_dir_path: artifacts/data_ingestion/test/test.csv
  column_names: ['cuisine_description', 'cuisine']
  tokenizer_name: distilbert-base-uncased
  model_name: artifacts/model_trainer/custom_model









